#ifndef STATES_H
#define STATES_H

/*global map for abbreviation to full state name */
std::map<string, string> theStatesAb =
{
pair<string, string>("AL",  "Alabama"), 
pair<string, string>("KY", "Kentucky"),
pair<string, string>("SC","SouthCarolina"),
pair<string, string>("OH", "Ohio"),
pair<string, string>("AK","Alaska"),
pair<string, string>("LA","Louisiana"),
pair<string, string>("OK", "Oklahoma"),
pair<string, string>("AZ", "Arizona"), 	
pair<string, string>("ME", "Maine"),
pair<string, string>("OR", "Oregon"),
pair<string, string>("AR", "Arkansas"), 	
pair<string, string>("MD","Maryland"),	
pair<string, string>("PA","Pennsylvania"),
pair<string, string>("MA","Massachusetts"), 	
pair<string, string>("PR","PuertoRico"),
pair<string, string>("CA","California"),	
pair<string, string>("MI","Michigan"), 	
pair<string, string>("RI","RhodeIsland"),
pair<string, string>("CO","Colorado"), 	
pair<string, string>("MN","Minnesota"),	
pair<string, string>("CT","Connecticut"),	
pair<string, string>("MS","Mississippi"),	
pair<string, string>("SD","SouthDakota"),
pair<string, string>("DE","Delaware"),	
pair<string, string>("MO","Missouri"),	
pair<string, string>("TN","Tennessee"),
pair<string, string>("DC","DistrictofColumbia"), 	
pair<string, string>("MT","Montana"), 	
pair<string, string>("TX", "Texas"),
pair<string, string>("FL","Florida"), 	
pair<string, string>("NE","Nebraska"), 
pair<string, string>("GA","Georgia"),
pair<string, string>("NV","Nevada"), 	
pair<string, string>("UT","Utah"),
pair<string, string>("GU","Guam"),	
pair<string, string>("NH","NewHampshire"), 	
pair<string, string>("VT","Vermont"),
pair<string, string>("HI","Hawaii"), 	
pair<string, string>("NJ","NewJersey"), 	
pair<string, string>("VA","Virginia"),
pair<string, string>("ID","Idaho"), 	
pair<string, string>("NM","NewMexico"),	
pair<string, string>("VI","VirginIslands"),
pair<string, string>("IL","Illinois"),	
pair<string, string>("NY","NewYork"),	
pair<string, string>("WA","Washington"),
pair<string, string>("IN","Indiana"),	
pair<string, string>("NC","NorthCarolina"), 	
pair<string, string>("WV","WestVirginia"),
pair<string, string>("IA","Iowa"),	
pair<string, string>("ND","NorthDakota"), 	
pair<string, string>("WI","Wisconsin"),
pair<string, string>("KS","Kansas"),	
pair<string, string>("WY","Wyoming")
};
#endif

